In [2]:
import numpy as np

In [4]:
a = np.array([10,20,30,40,50])

In [5]:
a

array([10, 20, 30, 40, 50])

In [6]:
type(a)

numpy.ndarray

In [8]:
a.shape

(5,)

In [10]:
## 2-D Array

In [13]:
a2 = np.array([[10,20,30],
             [40,50,60]])

In [14]:
a2

array([[10, 20, 30],
       [40, 50, 60]])

In [15]:
a2.shape

(2, 3)

In [16]:
## 3-D Array

In [22]:
a3 = np.array([[[10,20],[30,40],[50,60]]])

In [23]:
a3

array([[[10, 20],
        [30, 40],
        [50, 60]]])

In [24]:
a3.shape

(1, 3, 2)

In [25]:
a3.ndim

3

In [26]:
# To create a random number.

In [37]:
np.random.randint(low = 1, high = 50)

13

In [38]:
mat = np.random.randint(low = 1, high = 50, size = (3,3))

In [39]:
mat

array([[33,  3, 13],
       [28, 28, 46],
       [22,  7, 19]])

In [40]:
mat[0,0]

33

In [41]:
mat[-1,-1]

19

In [43]:
mat[1:3 , 1:3]

array([[28, 46],
       [ 7, 19]])